# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af3dae48d15d9d3fcf7074abbb71d9ec3b5bfe1b673be55fee5c8dd5cd36480668c55673bbe96116efcb1ccef3556c790d76263742e7203123b615537ceee52

test:
  secret_key_base: b2541f544a9c128896e61085c2f8c1c0b0139fc703ff80915e8614322a3ee46c84860967d916452cfc44c888f311f7efbc560139303cdf396696b1440d80ee88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
